version: "3.8"

services:
  web:
    build:
      context: ./frontend
    # env_file: .env
    ports:
      - "3000:3000"
    depends_on:
      - api

  api:
    build:
      context: ./backend
    # env_file: .env
    ports:
      - "8000:8000"
    depends_on:
      - db
    # command: sh /code/backend/entrypoint.sh
    # entrypoint: sh /code/deploy/docker/postgres/wait-for-postgres.sh
    # environment:
    #   DB_URL: mysql://db/procode

  db:
    image: mysql:8.0
    restart: always
    ports:
      - '3306:3306'
    expose:
      - '3306'
    environment:
      MYSQL_DATABASE: 'procode'
      # MYSQL_USER: 'user'
      # MYSQL_PASSWORD: 'user'
      # MYSQL_ROOT_PASSWORD: 'user'
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
    volumes:
      - "./config/my.conf:/etc/mysql/conf.d/config-file.cnf"
      - "./data:/var/lib/mysql:rw"

volumes:
  procode:
