version: "3.8"

services:
  web:
    build:
      context: ./frontend
      # dockerfile: Dockerfile.prod
    image: dockerprocode.azurecr.io/web
    ports:
      - "3000:3000"
    expose:
      - '3000'
    restart: always
    depends_on:
      - api
    # env_file: .env

  api:
    build:
      context: ./backend
    image: dockerprocode.azurecr.io/api
    restart: on-failure
    ports:
      - "8000:8000"
    expose:
      - '8000'
    depends_on:
      - db
    # env_file: .env

  db:
    image: mysql:8.0
    restart: always
    ports:
      - '3306:3306'
    expose:
      - '3306'
    environment:
      MYSQL_DATABASE: 'procode'
      # MYSQL_USER: 'user'
      # MYSQL_PASSWORD: 'user'
      # MYSQL_ROOT_PASSWORD: 'user'
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
    # env_file: .env
