version: "3.8"

services:
  web:
    build:
      context: ./frontend
    image: dockerprocode.azurecr.io/web
    ports:
      - "3000:3000"
    depends_on:
      - api

  api:
    build:
      context: ./backend
    image: dockerprocode.azurecr.io/api
    ports:
      - "8000:8000"
    depends_on:
      - db
  db:
    image: mysql:8.0
    restart: always
    ports:
      - '3306:3306'
    expose:
      - '3306'
    environment:
      MYSQL_DATABASE: 'mysql'
      # MYSQL_USERNAME: 'mysql'
      # MYSQL_PASSWORD: 'mysql'
      # MYSQL_ROOT_PASSWORD: 'mysql'
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
