version: "3.8"

services:
  web:
    build:
      context: ./frontend
      # dockerfile: Dockerfile.prod
    image: dockerprocode.azurecr.io/web

    # environment:
    #   API_URL: "https://api.myapp.com/"
    ports:
      - "3000:3000"
    expose:
      - '3000'
    restart: always
    depends_on:
      - api

  api:
    build:
      context: ./backend
    image: dockerprocode.azurecr.io/api
    restart: on-failure
    ports:
      - "8000:8000"
    expose:
      - '8000'
    depends_on:
      - db

  # db:
  #   image: 'postgres:latest'
  #   ports:
  #     - 5432:5432
  #   expose:
  #     - '5432'
  #   environment:
  #     POSTGRES_USER: mydatabaseuser
  #     POSTGRES_PASSWORD: mypassword
  #     POSTGRES_DB: mydatabase
  # db:
  #   image: mongo:4.0-xenial
  #   restart: always
  #   ports:
  #     - 27017:27017
  #   volumes:
  #     - procode:/data/db


  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: 'procode'
      # MYSQL_PASSWORD: ''
      MYSQL_ROOT_PASSWORD: ''
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
    ports:
      - '3306:3306'
    expose:
      - '3306'
    # volumes:
    #   - db_data: /var/lib/mysql
# volumes:
  # - db_data:
